language: cpp
os:
    - linux

dist: trusty

compiler:
    - gcc
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive  
  - sudo add-apt-repository --yes ppa:beineri/opt-qt56-trusty
  - sudo apt-get update -qq
  - apt-cache search qt5 --names-only
install:
  - sudo apt-get install -y -qq cmake lcov qt56base
script:
    - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target Coverage
