language: cpp
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive  
install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake lcov
  - apt-cache search qt5 --names-only
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5core5 libqt5widgets5 libqt5xml5 libqt5test5
script:
    - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target Coverage
