language: cpp
os:
    - linux

dist: trusty

compiler:
    - gcc
# Handle git submodules yourself
git:
  submodules: false


# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive  
  - sudo apt-get update -qq
  - apt-cache search libboost --names-only
# 
  - wget https://github.com/Viq111/travis-container-packets/releases/download/boost-1.57.0/boost.tar.bz2
  - tar -xjf boost.tar.bz2
  - rm boost.tar.bz2
  - ls -l  
  - export BOOST_ROOT=$(pwd)/boost
  - pip install --user cpp-coveralls

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt561-trusty'
    packages:
      - cmake
      - qt56base
      - lcov

install:
  - apt-cache search boost --names-only
  - source /opt/qt56/bin/qt56-env.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug .. 
    - cmake --build . 
    - cmake --build . --target Coverage

after_success:
    - coveralls --exclude lib --exclude tests --exclude ut --exclude mt --gcov-options '\-lp'
