language: cpp
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq qt5-default cmake lcov curl
script:
    - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target Coverage
