@startuml SearchResult - class diagram.png
namespace Search {
class Result { 
  + matchingWords[1...] : MatchingWord
  + count
}

class MatchingWord {
  + word_id
  + matching_letters: string
  + matching_pairs: pair<uint,uint>[1...]
}


MatchingWord -> Result
}
@enduml

