@startuml SearchResult - class diagram.png
namespace Search {
class Result { 
  + matchingWord[1...] : MatchingWord
  + count
}

class MatchingWord {
  + matchingLetters: string
  + matchingPairs: pair<uint,uint>[]
}


MatchingWord -> Result
}
@enduml

